name: "Frogbot Scan Repository"

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types:
      - trigger-frogbot-scan
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write
  pull-requests: write
  security-events: write

jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [ "main" ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Echo JFrog URL (For Debugging)
        run: echo "${{ secrets.JF_URL }}"

      - name: Run Frogbot Scan
        uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
